### ISSUE TITLE
'depthai.Pipeline' object has no attribute 'create'

### ISSUE THREAD

**Issue by mariasni** [geaxgx/depthai_blazepose#10]
Hello, I receive the error "depthai.Pipeline object has no attribute "create". Any ideas where the problem is? Thank you for your answer!

Pose detection blob file : C:\Users\Admin\depthai_blazepose-main\models\pose_detection_sh4.blob
Landmarks using blob file : C:\Users\Admin\depthai_blazepose-main\models\pose_landmark_full_sh4.blob
Internal camera FPS set to: 8
Sensor resolution: (1920, 1080)
Internal camera image size: 1792 x 1008 - crop_w:0 pad_h: 392
2254 anchors have been created
Creating pipeline...
Creating Color Camera...
Creating Pose Detection pre processing image manip...
Traceback (most recent call last):
  File "C:\Users\Admin\depthai_blazepose-main\examples\semaphore_alphabet\demo.py", line 51, in <module>
    pose = BlazeposeDepthai(input_src=args.input, lm_model=args.model)
  File "../..\BlazeposeDepthai.py", line 218, in __init__
    self.device.startPipeline(self.create_pipeline())
  File "../..\BlazeposeDepthai.py", line 287, in create_pipeline
    pre_pd_manip = pipeline.create(dai.node.ImageManip)
AttributeError: 'depthai.Pipeline' object has no attribute 'create'
[Finished in 3.5s with exit code 1]
[shell_cmd: python -u "C:\Users\Admin\depthai_blazepose-main\examples\semaphore_alphabet\demo.py"]
[dir: C:\Users\Admin\depthai_blazepose-main\examples\semaphore_alphabet]
[path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Brackets\command;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\OpenNI\Bin64;C:\Program Files\Nuitrack\nuitrack\nuitrack\bin;C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Admin\AppData\Local\Programs\Python\Python37\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Intel\Shared";C:\ProgramData\NVIDIA Corporation\Downloader\PostProcessing\GFE\a1b8f95e233fed392281175573cfcd07\GFExperience.NvStreamSrv\amd64\server;C:\Program Files\NVIDIA Corporation\NvStreamSrv;;C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Admin\.dotnet\tools]

**Comment by geaxgx** [comment]
Hi! 
It may be a problem with your version of depthai.
What is your version ? `pip3 list | grep depthai`
You should get: `depthai                       2.8.0.0.dev0+4f8b66e8f63dd4a1826337237636c05d3fa4a78e`
If not, first get a clone of https://github.com/luxonis/depthai-python , just type `git clone https://github.com/luxonis/depthai-python ` in the directory of your choice. 
Then follow the instructions there: https://github.com/geaxgx/depthai_blazepose#install

**Comment by mariasni** [comment]
Thanks! My version was 2.8.0.0, after reinstalling- it works perfectly! the important part was : python3 ./examples/install_requirements.py

All my best!
