### ISSUE TITLE
what's wrong with my demo.py ? 

### ISSUE THREAD

**Issue by bewithme** [geaxgx/depthai_blazepose#12]
self.device = dai.Device(self.create_pipeline())
RuntimeError: No available devices

**Comment by geaxgx** [comment]
You get this error message when the device is not connected or connection is not ok. Check your connection. Have you been able to run other depthai demo like this one: https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/#run-demo-script ?

**Comment by bewithme** [comment]
I have one webcam connected to my computer and it can work well with python open cv ,so it is strange to see that error

**Comment by geaxgx** [comment]
Have you followed the install requirements described there : https://docs.luxonis.com/en/latest/pages/tutorials/first_steps/#install-requirements (in particular if you are on linux, the commands in the Warning paragraph) ?

**Comment by bewithme** [comment]
Do I have to use OAK-1 or OAK-D ? I now just use ordinary webcam for testing.

**Comment by geaxgx** [comment]
Sure, you have to :-)
Like it is said in the first line of the README: 
_Running Google Mediapipe single body pose tracking models on DepthAI hardware (OAK-1, OAK-D, ...)._

I have another repo (with an older version of the models) that should run with your webcam: https://github.com/geaxgx/openvino_blazepose

**Comment by bewithme** [comment]
thank you so much， but can you tell me the relationship between Mediapipe and blazepose ?and where I can buy the OAK-1 ?

**Comment by geaxgx** [comment]
Closed.
