### ISSUE TITLE
Question about shift_x = 0 and shift_y = 0 in mediapipe_utils.py

### ISSUE THREAD

**Issue by flacle** [geaxgx/depthai_blazepose#17]
Hi,

I've been exploring your custom BlazePose implementation and have a question on L398 and L399 in 
https://github.com/geaxgx/depthai_blazepose/blob/a3ce15a25c82f4663e4d263c99d7f83ece59ab64/mediapipe_utils.py#L398

A couple of lines down on L408 and L409 (in the case of rotation != 0) the following assignments are given:
```
x_shift = (w * width * shift_x * cos(rotation) - h * height * shift_y * sin(rotation)) 
y_shift = (w * width * shift_x * sin(rotation) + h * height * shift_y * cos(rotation)) 
```
These 0 terms result in `x_shift` and `y_shift` to be zero as well.

Here are (I believe) the defaults set by mediapipe, https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/util/rect_transformation_calculator.proto - 5 and 6 seems a bit high. Does this mean that no shift is necessary in the BlazePose implementation of DepthAI?

**Comment by geaxgx** [comment]
5 and 6 are not default values but field numbers from the protocol number language (see https://developers.google.com/protocol-buffers/docs/proto#assigning). Default values in .proto files are defined with the following syntax [default =  ...] (like for scale_x or scale_y). For shift_x and shift_y, no default values are explicitly specified. The implicit default value is 0.

**Comment by flacle** [comment]
Thanks for the explanation, I'm not familiar with protocol buffers. So, if I understand correctly, there is not a need to explicitly set these to a non-zero value. Is there a use case then for when `x_shift` and `y_shift` are not by default 0?

I thought it was a mistake in the repository.

**Comment by geaxgx** [comment]
_>  Is there a use case then for when x_shift and y_shift are not by default 0?_
Yes. With the hand landmark module : https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/hand_landmark/palm_detection_detection_to_roi.pbtxt#L43

**Comment by flacle** [comment]
Right, ok understood, thank you for the clarification.
