### ISSUE TITLE
--show_3d isn't working

### ISSUE THREAD

**Issue by corlangerak** [geaxgx/depthai_blazepose#2]
Hi thank you so much for sharing this amazing demo! 

maybe its something I am doing wrong, but I cant seem to get --show_3d to work.
When I run it, it gives this error:
`Traceback (most recent call last):
  File "/Users/corlangerak/depthai_blazepose/BlazeposeDepthai.py", line 626, in <module>
    ht.run()
  File "/Users/corlangerak/depthai_blazepose/BlazeposeDepthai.py", line 412, in run
    device = dai.Device(self.create_pipeline())
  File "/Users/corlangerak/depthai_blazepose/BlazeposeDepthai.py", line 213, in create_pipeline
    pd_nn.setBlobPath(str(Path(self.pd_path).resolve().absolute()))
RuntimeError: NeuralNetwork node | Blob at path: /Library/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/Resources/models/pose_detection.blob doesn't exist
`
Am I missing something? the path is actually defined in the code, so I do not really understand.
Thanks again!

**Comment by geaxgx** [comment]
I could reproduced the problem by running the script from a directory which is not the directory where BlazeposeDepthai.py is located. It is not related to the argument '--show_3d'. Until I apply a fix, in your case, just run:
cd /Users/corlangerak/depthai_blazepose
python BlazeposeDepthai.py --show_3d

**Comment by geaxgx** [comment]
I have applied a fix which enables to call the script from whatever working directory you want.
