### ISSUE TITLE
Problem with Spatial Location

### ISSUE THREAD

**Issue by Otabiel** [geaxgx/depthai_blazepose#21]
Hi, I come back to you for a simple question. I'm trying to add to your library the possibility to have the approximate position in millimeters of a specific point as proposed here https://docs.luxonis.com/projects/api/en/latest/samples/SpatialDetection/spatial_location_calculator/

But when I try it I've got non realistic value for x and y. As I understand the value are calculated compared to the center of the frame. But I've got too similarly values and I don't know how to trouble shot it. Have you done something special for making it work for the center hips or shoulders ?

I'm trying with this two point :
![image](https://user-images.githubusercontent.com/61697964/181000027-625c1f0c-c094-4a1e-ab36-0e9f7495f596.png)

For each point their real position in frame are : `[1149, 842] and [1256, 405]`

And my spatial locator give me the respective true positions : 
`[-252.84371948242188, -120.76118469238281, 1234.7139892578125] and§ [-255.68605041503906, -121.71033477783203, 1234.7718505859375]`

For the z position it seems to be legit, cause far away of the camera I go bigger the distance is..

I don't know if you will be able to help me

**Comment by geaxgx** [comment]
Is your code visible somewhere so that I can have a look ?

**Comment by Otabiel** [comment]
I can put the add I've made in your library here : 

In `create_pipeline` I've add : 
```python
            xoutSpatialData = pipeline.create(dai.node.XLinkOut)
            xinSpatialCalcConfig = pipeline.create(dai.node.XLinkIn)
            xoutSpatialData.setStreamName("spatialData")
            xinSpatialCalcConfig.setStreamName("spatialCalcConfig")

            spatial_location_calculator.out.link(xoutSpatialData.input)
            xinSpatialCalcConfig.out.link(spatial_location_calculator.inputConfig)
            stereo.depth.link(spatial_location_calculator.inputDepth)
```

Then I've created two queue
```python
            self.q_spatial_calc = self.device.getOutputQueue(name="spatialData", maxSize=4, blocking=False)
            self.q_spatial_conf = self.device.getInputQueue("spatialCalcConfig")
```
And then create this function :
```python
    def roi_data(self, point):
        top_left = dai.Point2f(point[0], point[1])
        bottom_right = dai.Point2f(point[0], point[1])

        config = dai.SpatialLocationCalculatorConfigData()
        config.depthThresholds.lowerThreshold = 100
        config.depthThresholds.upperThreshold = 10000
        config.roi = dai.Rect(top_left, bottom_right)
        config.calculationAlgorithm = dai.SpatialLocationCalculatorAlgorithm.AVERAGE
        cfg = dai.SpatialLocationCalculatorConfig()
        cfg.addROI(config)
        self.q_spatial_conf.send(cfg)

        spatial_data = self.q_spatial_calc.get().getSpatialLocations()
        xyz = spatial_data[0].spatialCoordinates
        return [float(xyz.x), float(xyz.y), float(xyz.z)]

        # for depth_data in spatial_data:
        #     return [depth_data.spatialCoordinates.x,
        #             depth_data.spatialCoordinates.y,
        #             depth_data.spatialCoordinates.z]
```

And that's the output of roi_data that give me the point printed in the first comment. And I observe too that sometimes he blocked all x y and z value at 0.0

**Comment by geaxgx** [comment]
Your top_left is the same as bottom_right. I am not sure how the SpatialLocationCalculator behaves in that case, but usually we use a square zone, something like:
```
top_left = dai.Point2f(point[0]-d, point[1]-d)
bottom_right = dai.Point2f(point[0]+d, point[1]+d)
```
And `d` is chosen such that the square zone belongs only to the object (here the body part) we are interested in. If the zone is a mix of body pixels and background pixels and you use the AVERAGE algorithm, the z will probably be not accurate. So you don't want the zone to be too large.

Yet I don't think that explains the wrong x and y you observe. I can't see other problem in the code you shared. Without seeing the whole code, I can't say more.

**Comment by Otabiel** [comment]
Thanks for your answer as always ! :D

I've already tried with a rectangle as your solution describe, and it was the same. It's I in my code I removed it to try without.
But I found a way more logical two calculate the exact distance between two point without using SpatialLocationCalculator.

So I'll continue with that instead of troubleshooting my problem.
