### ISSUE TITLE
Error in the edge mode

### ISSUE THREAD

**Issue by AleBasso80** [geaxgx/depthai_blazepose#37]
Hi,
first of all thank you for your great work!

I got a problem that I'm not able to explain. I'm working with an OAK-D-PRO FF.

If I use the edge mode specifying also the xyz flag everything is fine, but if I just launch python3 demo.py -e (without -xyz) I always get this error:

[18443010E1A6AB0F00] [3.6] [7.446] [system] [critical] Fatal error. Please report to developers. Log: 'ResourceLocker' '358'
Traceback (most recent call last):
  File "/home/user/Development/body/depthai_blazepose/depthai_blazepose/demo.py", line 65, in <module>
    frame, body = tracker.next_frame()
  File "/home/user/Development/body/depthai_blazepose/depthai_blazepose/BlazeposeDepthaiEdge.py", line 486, in next_frame
    res = marshal.loads(self.q_manager_out.get().getData())
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'manager_out' (X_LINK_ERROR)'

Do you have any idea?

Thank you!

**Comment by geaxgx** [comment]
Sorry for the late reply. 
I am able to reproduce exactly the problem (in my case with an OAKD lite). It seems to be related to the latest depthai version (2.21.2.0). Recently I have not followed the updates on the depthai side so I am not aware of the changes brought by this version. I will ask to the Luxonis team. In the meantime, may I suggest you to downgrade to a previous version: 
`pip install depthai==2.20.2`
Note that with the 2.20.2, you can still get the 'ResourceLocker' '358' error in rare occasions (when the face is very close to the camera).

**Comment by AleBasso80** [comment]
Thank you very much for your kind feedback.

I'll try what you suggested.

I'm closing the issue, please let me know should you get any feedback from Luxonis.

Cheers!

**Comment by stormboy** [comment]
Has there been any progress on this issue, @geaxgx ?
I am getting the same, and on analysing the rotated rectangle going into the ImageManip config, have found no specific patterns that cause the crash. Just that the odds seem to be increased with greater angles (towards 45 degrees) and moving off the edge of the bounds of the video feed.

I see that someone at DepthAI have fobbed off a couple of reports of the same thing, saying to go back to the author of the code (you), but considering behaviour has clearly changed from one version of DepthAI to another, you would think that team would take it more seriously.
