### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EltonCN** [geaxgx/depthai_blazepose#8]
Hi!

I'm from ReDrawing team for the OpenCV AI 2021 competition, and we used a part of this repository code. We noticed that the repository don't have any license, so we can't derive from it, technically not even run it.

If not on purpose, could you please add a license? We also used your 
[depthai_hand_tracker](https://github.com/geaxgx/depthai_hand_tracker) project. [Here](https://choosealicense.com/) some help about licenses.

Our project repository: [link](https://github.com/ReDrawing/redrawing)

**Comment by geaxgx** [comment]
I am not familiar with licensing, that's probably why I always forget to include one :-)) 
Here, as I am using models from Mediapipe which under Apache 2.0 license, do I need to use the same or can I use directly MIT license ? It is not clear to me. Do you know ?

**Comment by EltonCN** [comment]
I'm not too familiar either. For what I know, yes, you can use the MIT license, but you need to keep the original license file and also explicitly say if you modified any original file.

**Comment by geaxgx** [comment]
Repo updated with MIT license. Will do on depthai_hand_tracker too.
